# -*- coding: utf-8 -*-
"""NLP_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVai6bTec_ssQarQaP83NK6YGAz8x9ep
"""

from collections import defaultdict #A dict that gives a default value if a key doesn’t exist (avoids KeyErrors).
import matplotlib.pyplot as plt

class TrieNode:
    def __init__(self):
        self.children = {} #dict to store the child nodes (next letters)
        self.freq = 0      # no of words which pass through this node
        self.is_end = False # mark the node if it is a end of a word

class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word):
        node = self.root
        for ch in word:
            if ch not in node.children:
                node.children[ch] = TrieNode()
            node = node.children[ch]             #
            node.freq += 1                       # increment frequency (path count)
        node.is_end = True                       # mark word completion

prefix_trie = Trie()
suffix_trie = Trie()

with open("/content/sample_data/brown_nouns.txt", "r") as f:
    words = [w.strip().lower() for w in f if w.strip()]

for w in words:
    prefix_trie.insert(w)
    suffix_trie.insert(w[::-1])  #go reverse , check suffix

freq = defaultdict(int)                #key = word, value = count
for w in words:
    freq[w] += 1
print(freq.items())

sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)
# sorted sorts any iterable
# key is to sort the data wrt x[1] which is freq
print(sorted_freq)

top_words, counts = zip(*sorted_freq[:100])
plt.figure(figsize=(12,6))
plt.bar(top_words, counts)
plt.xticks(rotation=90)
plt.title("Top 100 Frequent Words")
plt.show()

class TrieNode:
    def __init__(self):
        self.children = dict()
        self.count = 0  # Number of words passing through this node

class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word):
        node = self.root
        node.count += 1
        for char in word:
            if char not in node.children:
                node.children[char] = TrieNode()
            node = node.children[char]
            node.count += 1

    def find_branch_point(self, word):
        node = self.root
        prefix = ""
        max_branches = -1
        branch_point = 0
        total_nodes = 0
        for idx, char in enumerate(word):
            node = node.children[char]
            branches = len(node.children)
            # Record the branching node with highest number of branches
            if branches > max_branches:
                max_branches = branches
                branch_point = idx + 1
            total_nodes += 1
        return branch_point, max_branches / max(1, total_nodes)  # Index after stem, branch freq

# Helper to process both trie types
def process_trie(words, reverse=False):
    trie = Trie()
    # Insert words
    for w in words:
        to_insert = w[::-1] if reverse else w
        trie.insert(to_insert)
    # Find split for each word
    splits = []
    for w in words:
        to_check = w[::-1] if reverse else w
        split_idx, branch_freq = trie.find_branch_point(to_check)
        if reverse:
            stem = w[::-1][split_idx:][::-1]
            suffix = w[::-1][:split_idx][::-1]
        else:
            stem = w[:split_idx]
            suffix = w[split_idx:]
        splits.append((w, stem, suffix, branch_freq))
    return splits

# Example word list
with open("/content/sample_data/brown_nouns.txt", "r") as f:
    words = [w.strip().lower() for w in f if w.strip()]


# Prefix trie processing
prefix_results = process_trie(words, reverse=False)
# Suffix trie processing
suffix_results = process_trie(words, reverse=True)

print("Prefix Trie Splits:")
for w, stem, suffix, prob in prefix_results:
    print(f"{w} = {stem} + {suffix}  ") #(branch-prob={prob:.2f})

print("\nSuffix Trie Splits:")
for w, stem, suffix, prob in suffix_results:
    print(f"{w} = {stem} + {suffix} ")

import re
from itertools import islice
def sentence_tokenizer(text):
    return re.split(r'(?<=[।!?|])\s+', text.strip())
#  ?<=  Lookbehind means: “Match something only if it is immediately preceded by a certain pattern.”
# strip - remove all the space in start , end of sentence
# r' ' - raw string
# Word tokenizer
def word_tokenizer(sentence):
    pattern = r'''(?x)                       #(?x) - tells python re to ignore space , comment in this string
        (https?://[^\s]+)                    # URLs  #:// takes the literal character //
      | (\w+@\w+\.\w+)                       # Emails
      | (\d{1,2}[-/]\d{1,2}[-/]\d{2,4})      # Dates
      | (\d+\.\d+)                           # Decimals
      | (\d+)                                # Whole numbers
      | ([\u0900-\u097F]+)                   # Devanagari (Marathi/Hindi) words
      | ([a-zA-Z]+)                          # English words
      | ([।.,!?;:"'\-—()])                   # Punctuation
    '''
    tokens = re.findall(pattern, sentence)
    #When used with re.findall, each token will go into a separate group.
    # Flatten the list of tuples into a single list
    return [t for group in tokens for t in group if t]

from datasets import load_dataset
dataset = load_dataset("ai4bharat/IndicCorpV2",split = "mar_Deva" , encoding = 'utf-8-sig', streaming = True)
display(dataset)

max_examples = 100000
tokenized_dataset = []  # a list to hold all tokens from all examples
# Safely iterate over streaming dataset with limit
for example in islice(dataset, max_examples): # word, freq
    text = example["text"]
    sentences = sentence_tokenizer(text)
    for sentence in sentences:
        tokens = word_tokenizer(sentence)
        if tokens:
            tokenized_dataset.extend(tokens)

import matplotlib.font_manager as fm

for font in fm.findSystemFonts(fontpaths=None, fontext='ttf'):
    if "Noto" and "lohit-devanagari" in font :
        print(font)

!apt-get update -qq
!apt-get install -y fonts-noto fonts-lohit-deva

import matplotlib.pyplot as plt
from matplotlib import font_manager as fm

# Load a font that supports Marathi (after installing fonts-noto)
mar_font = fm.FontProperties(fname='/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf')

# 1. Count word frequencies (no libraries, no collections)
freq = {}
for word in tokenized_dataset:
    if word in freq:
        freq[word] += 1
    else:
        freq[word] = 1

# 2. Plot top 100 most common words
top_100 = sorted(freq.items(), key=lambda x: x[1], reverse=True)[:100]
words_100 = [item[0] for item in top_100]
freqs_100 = [item[1] for item in top_100]

plt.figure(figsize=(15, 7))
plt.bar(words_100, freqs_100)
plt.xticks(rotation=90, fontproperties=mar_font)  # Marathi font for x-axis
plt.xlabel("शब्द", fontproperties=mar_font)       # Marathi label for "Word"
plt.ylabel("वारंवारता", fontproperties=mar_font)  # Marathi label for "Frequency"
plt.title("सर्वाधिक १०० वारंवार येणारे शब्द", fontproperties=mar_font)  # Marathi title
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from matplotlib import font_manager as fm

# Marathi font
mar_font = fm.FontProperties(fname='/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf')

# Function to compute frequency dictionary
def compute_freq(tokens):
    freq = {}
    for word in tokens:
        if word in freq:
            freq[word] += 1
        else:
            freq[word] = 1
    return freq

# Function to remove stop words based on threshold
def remove_stop_words(freq_dict, threshold):
    return {word: count for word, count in freq_dict.items() if count <= threshold}

# Original frequencies
freq = compute_freq(tokenized_dataset)

# Define thresholds
thresholds = [100, 1000, 5000]

for threshold in thresholds:
    # Remove stop words based on threshold
    filtered_freq = remove_stop_words(freq, threshold)

    # Get top 100 most common words after stop word removal
    top_100 = sorted(filtered_freq.items(), key=lambda x: x[1], reverse=True)[:100]
    words_100 = [item[0] for item in top_100]
    freqs_100 = [item[1] for item in top_100]

    # Plot
    plt.figure(figsize=(15, 7))
    plt.bar(words_100, freqs_100)
    plt.xticks(rotation=90, fontproperties=mar_font)
    plt.xlabel("Word", fontproperties=mar_font)
    plt.ylabel("Frequency")
    plt.title(f"Top 100 Most Frequent Words (Stop words removed: freq ≤ {threshold})", fontproperties=mar_font)
    plt.tight_layout()
    plt.show()

"Dataset Tokenization Loop": {
  "prefix": "data_loop",
  "body": [
    "max_examples = 100000",
    "tokenized_sentences = []",
    "total_words = 0",
    "total_chars = 0",
    "unique_tokens = set()",
    "",
    "# Safely iterate over streaming dataset with limit",
    "for example in islice(dataset, max_examples):  # word, freq",
    "    text = example[\"text\"]",
    "    sentences = sentence_tokenizer(text)",
    "    for sentence in sentences:",
    "        tokens = word_tokenizer(sentence)",
    "        if tokens:",
    "            tokenized_sentence = \" \".join(tokens)",
    "            tokenized_sentences.append(tokenized_sentence)",
    "            total_words += len(tokens)",
    "            total_chars += sum(len(t) for t in tokens)",
    "            unique_tokens.update(tokens)"
  ],
  "description": "Loop to tokenize sentences and collect statistics from streaming dataset"
}